import { prisma } from "@/lib/prisma";

// Server-side layer for the SEO consent & disclosure review:
//   - persistence of findings + sign-off decisions (raw SQL, see note below)
//   - applying an accepted rewrite to a Sanity DRAFT
//   - reporting whether a change is still draft-only or has been published
//
// NOTE ON RAW SQL: this uses $queryRaw rather than the generated Prisma model
// accessor. The model exists in schema.prisma and the table is created by the
// deploy's `prisma db push`, but `prisma generate` could not be run in the
// authoring environment, so the typed accessor is not available here. The SQL
// below is parameterised throughout — no interpolation of user input.

export const SANITY_PROJECT = "oy7f1h9b";
export const SANITY_DATASET = "production";
const API = `https://${SANITY_PROJECT}.api.sanity.io/v2021-06-07`;

export interface FindingRow {
  id: string;
  post_id: string;
  slug: string;
  title: string;
  segment_id: string;
  field_label: string;
  layer: string;
  term: string | null;
  disposition: string;
  confidence: string | null;
  original_text: string;
  proposed_text: string | null;
  final_text: string | null;
  reader_takeaway: string | null;
  decision: string | null;
  note: string | null;
  decided_by: string | null;
  decided_at: Date | null;
  rules_hash: string;
  model: string;
  applied_to_draft: boolean;
  applied_at: Date | null;
  sanity_path: string | null;
}

// --- Sanity reads (public dataset, no token needed) ------------------------
async function groq<T>(query: string, params: Record<string, unknown> = {}): Promise<T> {
  const res = await fetch(`${API}/data/query/${SANITY_DATASET}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ query, params }),
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`Sanity query failed: ${res.status}`);
  return (await res.json()).result as T;
}

/**
 * Publish status for a set of documents.
 *
 * Sanity deletes `drafts.<id>` when a document is published, so the presence of
 * a draft is the signal: draft exists => the change is still unpublished.
 * We additionally check whether the published document now contains the new
 * text, which distinguishes "published" from "draft discarded".
 */
export async function getPublishStatus(
  postIds: string[],
): Promise<Record<string, { draftExists: boolean; publishedUpdatedAt: string | null }>> {
  if (postIds.length === 0) return {};
  const draftIds = postIds.map((id) => `drafts.${id}`);
  const rows = await groq<
    { published: { _id: string; _updatedAt: string }[]; drafts: { _id: string }[] }
  >(
    `{
      "published": *[_id in $ids]{_id, _updatedAt},
      "drafts": *[_id in $draftIds]{_id}
    }`,
    { ids: postIds, draftIds },
  );
  const draftSet = new Set((rows.drafts || []).map((d) => d._id.replace(/^drafts\./, "")));
  const out: Record<string, { draftExists: boolean; publishedUpdatedAt: string | null }> = {};
  for (const id of postIds) {
    const pub = (rows.published || []).find((p) => p._id === id);
    out[id] = { draftExists: draftSet.has(id), publishedUpdatedAt: pub?._updatedAt ?? null };
  }
  return out;
}

// --- Sanity write (requires a token) ---------------------------------------
export class SanityTokenMissing extends Error {
  constructor() {
    super(
      "SANITY_WRITE_TOKEN is not configured. Accepting a finding cannot update the Sanity draft until an Editor-scoped write token is set in the environment.",
    );
    this.name = "SanityTokenMissing";
  }
}

/**
 * Apply a single rewrite to the DRAFT of a published document.
 *
 * Never touches the published document and never publishes: it seeds
 * `drafts.<id>` from the published doc if absent (`createIfNotExists`), then
 * patches only the given path. The caller must have verified the original text
 * anchors verbatim.
 */
export async function applyToDraft(opts: {
  postId: string;
  path: string;
  newValue: string;
}): Promise<{ draftId: string; transactionId: string }> {
  const token = process.env.SANITY_WRITE_TOKEN;
  if (!token) throw new SanityTokenMissing();

  const { postId, path, newValue } = opts;
  const draftId = `drafts.${postId}`;

  // Guard: the path is generated by our own planner, but validate anyway so a
  // corrupted row can never smuggle arbitrary content into a mutation path.
  if (!/^[A-Za-z0-9_.[\]"=\-]+$/.test(path)) {
    throw new Error(`Refusing to patch: unsafe path ${JSON.stringify(path)}`);
  }

  // Seed the draft from the published document if it does not exist yet —
  // this is what the Studio does when you first edit a published doc.
  const published = await groq<Record<string, unknown> | null>(`*[_id == $id][0]`, { id: postId });
  if (!published) throw new Error(`Published document ${postId} not found`);
  const draftSeed = { ...published, _id: draftId };
  delete (draftSeed as Record<string, unknown>)._rev;

  const res = await fetch(`${API}/data/mutate/${SANITY_DATASET}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
    body: JSON.stringify({
      mutations: [
        { createIfNotExists: draftSeed },
        { patch: { id: draftId, set: { [path]: newValue } } },
      ],
    }),
  });
  if (!res.ok) {
    throw new Error(`Sanity mutate failed: ${res.status} ${await res.text()}`);
  }
  const json = (await res.json()) as { transactionId: string };
  return { draftId, transactionId: json.transactionId };
}

// --- persistence -----------------------------------------------------------
export async function getFindingsForSlug(slug: string): Promise<FindingRow[]> {
  return prisma.$queryRaw<FindingRow[]>`
    SELECT * FROM seo_review_findings WHERE slug = ${slug} ORDER BY id ASC`;
}

export async function getFinding(id: string): Promise<FindingRow | null> {
  const rows = await prisma.$queryRaw<FindingRow[]>`
    SELECT * FROM seo_review_findings WHERE id = ${id} LIMIT 1`;
  return rows[0] ?? null;
}

/** Every change that has actually been written to a draft — the audit log. */
export async function getAppliedChanges(): Promise<FindingRow[]> {
  return prisma.$queryRaw<FindingRow[]>`
    SELECT * FROM seo_review_findings
    WHERE applied_to_draft = true
    ORDER BY applied_at DESC`;
}

export async function recordDecision(opts: {
  id: string;
  decision: string | null;
  note: string | null;
  finalText: string | null;
  decidedBy: string | null;
}): Promise<void> {
  await prisma.$executeRaw`
    UPDATE seo_review_findings
    SET decision = ${opts.decision},
        note = ${opts.note},
        final_text = ${opts.finalText},
        decided_by = ${opts.decidedBy},
        decided_at = ${opts.decision ? new Date() : null},
        updated_at = NOW()
    WHERE id = ${opts.id}`;
}

export async function markApplied(id: string, path: string): Promise<void> {
  await prisma.$executeRaw`
    UPDATE seo_review_findings
    SET applied_to_draft = true, applied_at = NOW(), sanity_path = ${path}, updated_at = NOW()
    WHERE id = ${id}`;
}

export async function tableExists(): Promise<boolean> {
  const rows = await prisma.$queryRaw<{ t: string | null }[]>`
    SELECT to_regclass('public.seo_review_findings')::text AS t`;
  return Boolean(rows[0]?.t);
}
